name: ie-bank-infra

on:
  workflow_dispatch:
  push:
      paths:
        - '!scripts/**'

env:
  RESOURCE_GROUP_UAT: BCSAI2024-DEVOPS-STUDENTS-B-UAT
  SUBSCRIPTION_ID_UAT: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: adelatorre

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Lint Bicep code 
    - name: Run Bicep linter
      run: az bicep build --file ./main.bicep

  deploy-uat:
#   if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'UAT'

    steps:

      # Checkout code
    - uses: actions/checkout@main
    
      # Log into Azure
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      # List Resource Groups

    - name: List Resource Groups
      run: az group list --subscription ${{ env.SUBSCRIPTION_ID_UAT }}

      # Show environment variables and secrets
    - name: Show environment variables and secrets
      run: |
        echo "ENV: ${{ vars.ENV }}"
        echo "DBHOST: ${{ vars.DBHOST }}"
        echo "DBNAME: ${{ vars.DBNAME }}"
        echo "DBPASS: ${{ secrets.DBPASS }}"
        echo "DBUSER: ${{ secrets.DBUSER }}"
        echo "FLASK_APP: ${{ vars.FLASK_APP }}"
        echo "FLASK_RUN_PORT: ${{ vars.FLASK_RUN_PORT }}"
        echo "FLASK_DEBUG: ${{ vars.FLASK_DEBUG }}"
      env:
        DBPASS: ${{ secrets.DBPASS }}
        DBUSER: ${{ secrets.DBUSER }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID_UAT }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_UAT }}
        template: ./main.bicep
        parameters: ./parameters/uat.parameters.json appServiceAPIEnvVarENV=${{ vars.ENV }} appServiceAPIEnvVarDBHOST=${{ vars.DBHOST }} appServiceAPIEnvVarDBNAME=${{ vars.DBNAME }} appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }} appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }} appServiceAPIDBHostFLASK_APP=${{ vars.FLASK_APP }} appServiceAPIDBHostFLASK_RUN_PORT=${{ vars.FLASK_RUN_PORT }} appServiceAPIDBHostFLASK_DEBUG=${{ vars.FLASK_DEBUG }}
        deploymentName: ${{ env.USER_ALIAS }}